fix(deploy): Manually query commit status to prevent failures from skipped checks
#### What's the problem?

Following the optimization in #4443, we now skip duplicate CI checks for `push` events. While this improves efficiency, it has an unintended side effect: the commit status for these skipped checks is marked as `skipped`.

Our deployment system interprets a `skipped` status as a failure or an inconclusive state, which blocks the deployment process.

#### How does this PR solve it?

To resolve this, this PR modifies our deployment logic:

1.  **Manual Pre-check:** Before initiating a deployment, we now manually query the commit's status to ensure all required checks have passed (while correctly handling the `skipped` state).
2.  **Bypass Validation:** The deployment step itself is updated to bypass the built-in commit status validation, as we've already confirmed its validity in the pre-check phase.

This approach ensures that deployments are no longer blocked by `skipped` statuses, while still maintaining the integrity of our deployment checks.

**Related Issues:**
*   Context: #4443

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -9,10 +9,15 @@ permissions: {}
 
 jobs:
   deploy:
-    permissions:
-      deployments: write
     runs-on: ubuntu-latest
     steps:
+      - name: Check Commit Status
+        run: |
+          commit_state=$(curl -sf -H 'Accept: application/json' 'https://github.com/${{ github.repository }}/commits/deferred_commit_data/${{ github.ref_name }}' | jq -r '.deferredCommits[0].statusCheckStatus.state // "not_found"')
+          if [[ "$commit_state" != "success" ]]; then
+            echo "::error::Status is '$commit_state'."
+            exit 1
+          fi
       - name: Create Deployment
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
         with:
@@ -21,4 +26,5 @@ jobs:
             await github.rest.repos.createDeployment({
               ...context.repo,
               ref: context.ref.slice(11),
+              required_contexts: []
             });
